adjective1 = input("Enter an adjective:")
noun = input("Enter a noun:")
adjective_2= input("Enter an ajdective:")
verb = input("Enter a verb:")
adjective2 =input("Enter an adjective:")

print(f"Yesterday i went to a  {adjective1} water park")
print(f"There I saw {noun} ")
print(f"{noun} was {adjective2} and {verb}ing")
print(f"I was {adjective_2}")